function normalizeCssColor(value: string): string {
  const color = value?.trim();
  if (!color) return "";

  const canvas = document.createElement("canvas");
  const context = canvas.getContext("2d");
  if (!context) return color;

  context.fillStyle = "#000000";
  context.fillStyle = color;

  const normalized = context.fillStyle;
  return normalized || color;
}

function sanitizeCloneStyles(source: HTMLElement, clone: HTMLElement) {
  const sourceElements = [source, ...Array.from(source.querySelectorAll("*"))];
  const cloneElements = [clone, ...Array.from(clone.querySelectorAll("*"))];

  const colorProperties = [
    "color",
    "backgroundColor",
    "borderTopColor",
    "borderRightColor",
    "borderBottomColor",
    "borderLeftColor",
    "outlineColor",
    "textDecorationColor",
    "columnRuleColor",
    "fill",
    "stroke",
  ] as const;

  sourceElements.forEach((sourceElement, index) => {
    const cloneElement = cloneElements[index];
    if (!(cloneElement instanceof HTMLElement)) return;

    const computed = window.getComputedStyle(sourceElement);
    const style = cloneElement.style;

    for (const property of colorProperties) {
      const value = computed[property];
      if (!value) continue;

      if (value.includes("oklch(") || value.includes("oklab(") || value.includes("lab(") || value.includes("lch(")) {
        const normalized = normalizeCssColor(value);
        if (normalized) {
          style.setProperty(
            property.replace(/[A-Z]/g, (match) => `-${match.toLowerCase()}`),
            normalized,
            "important"
          );
        }
      }
    }

    // html2canvas can fail on advanced shadows/effects generated by newer CSS.
    if (computed.boxShadow && computed.boxShadow !== "none") {
      style.setProperty("box-shadow", "none", "important");
    }

    if (computed.textShadow && computed.textShadow !== "none") {
      style.setProperty("text-shadow", "none", "important");
    }
  });
}

async function capturePrescription(element: HTMLElement): Promise<HTMLCanvasElement> {
  const [{ default: html2canvas }] = await Promise.all([
    import("html2canvas"),
  ]);

  if (!html2canvas) {
    throw new Error("PDF renderer could not be loaded.");
  }

  if (document.fonts?.ready) {
    await document.fonts.ready;
  }

  await new Promise<void>((resolve) => {
    requestAnimationFrame(() => {
      requestAnimationFrame(() => resolve());
    });
  });

  const clone = element.cloneNode(true) as HTMLElement;
  const width = Math.max(element.scrollWidth, element.offsetWidth, 794);

  clone.style.width = `${width}px`;
  clone.style.maxWidth = "none";
  clone.style.minHeight = `${Math.max(element.scrollHeight, 1123)}px`;
  clone.style.margin = "0";
  clone.style.position = "absolute";
  clone.style.left = "-100000px";
  clone.style.top = "0";
  clone.style.background = "#ffffff";
  clone.style.boxShadow = "none";
  clone.style.transform = "none";

  sanitizeCloneStyles(element, clone);

  const holder = document.createElement("div");
  holder.style.position = "absolute";
  holder.style.left = "0";
  holder.style.top = "0";
  holder.style.width = `${width}px`;
  holder.style.background = "#ffffff";
  holder.style.zIndex = "-1";
  holder.appendChild(clone);
  document.body.appendChild(holder);

  try {
    return await html2canvas(clone, {
      scale: Math.min(window.devicePixelRatio || 1, 2),
      backgroundColor: "#ffffff",
      useCORS: true,
      allowTaint: false,
      logging: false,
      imageTimeout: 15000,
      width,
      windowWidth: width,
      scrollX: 0,
      scrollY: 0,
      removeContainer: true,
      onclone: (clonedDocument) => {
        clonedDocument.documentElement.style.background = "#ffffff";
        clonedDocument.body.style.background = "#ffffff";
      },
    });
  } finally {
    holder.remove();
  }
}

export async function buildPrescriptionPdfBlob(
  element: HTMLElement
): Promise<Blob> {
  const canvas = await capturePrescription(element);
  const { jsPDF } = await import("jspdf");

  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
    compress: true,
  });

  const margin = 8;
  const pageWidth = 210;
  const pageHeight = 297;
  const contentWidth = pageWidth - margin * 2;
  const contentHeight = pageHeight - margin * 2;

  const pixelsPerPage = Math.max(
    1,
    Math.floor((canvas.width * contentHeight) / contentWidth)
  );

  let sourceY = 0;
  let pageIndex = 0;

  while (sourceY < canvas.height) {
    const sliceHeight = Math.min(
      pixelsPerPage,
      canvas.height - sourceY
    );

    const pageCanvas = document.createElement("canvas");
    pageCanvas.width = canvas.width;
    pageCanvas.height = sliceHeight;

    const pageContext = pageCanvas.getContext("2d");
    if (!pageContext) {
      throw new Error("Could not prepare the prescription PDF page.");
    }

    pageContext.fillStyle = "#ffffff";
    pageContext.fillRect(0, 0, pageCanvas.width, pageCanvas.height);
    pageContext.drawImage(
      canvas,
      0,
      sourceY,
      canvas.width,
      sliceHeight,
      0,
      0,
      canvas.width,
      sliceHeight
    );

    const imageData = pageCanvas.toDataURL("image/jpeg", 0.94);
    const imageHeight =
      (sliceHeight * contentWidth) / canvas.width;

    if (pageIndex > 0) {
      pdf.addPage();
    }

    pdf.addImage(
      imageData,
      "JPEG",
      margin,
      margin,
      contentWidth,
      Math.min(imageHeight, contentHeight),
      undefined,
      "FAST"
    );

    sourceY += sliceHeight;
    pageIndex += 1;
  }

  return pdf.output("blob");
}

export function downloadBlob(blob: Blob, filename: string) {
  if (!(blob instanceof Blob) || blob.size === 0) {
    throw new Error("The generated PDF is empty.");
  }

  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");

  anchor.href = url;
  anchor.download = filename;
  anchor.rel = "noopener";
  anchor.style.display = "none";

  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();

  window.setTimeout(() => URL.revokeObjectURL(url), 1500);
}
